// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LyBooking.DTO
{
    public partial class GlueChemicalDto
    {
        public decimal Id { get; set; }
        public string GlueGuid { get; set; }
        public string ChemicalGuid { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public DateTime? DeleteDate { get; set; }
        public decimal? DeleteBy { get; set; }
        public decimal? Status { get; set; }
        public string Guid { get; set; }
        public string Position { get; set; }
        public double Percentage { get; set; }
    }
}