export interface BookingDetail {
    id: number;
    siteGuid: string;
    hallGuid: string | null;
    workOrderGuid: string;
    roomGuid: string;
    hallType: string;
    roomType: string;
    bookingTimeS: any;
    bookingTimeE: any;
    bookingDate: any;
    funeralDirector: string;
    funeralMemo: string;
    prepareRice: string;
    prepareVegetarian: string;
    prepareFlower: string;
    prepareFruit: string;
    prepareTea: string;
    prepareFloral: string;
    chantingType: string;
    offerings: string;
    mageMemo: string;
    mageMoney: string;
    inOut: string;
    mageMonk: number;
    orderMeal: number;
    mouseMonk: number;
    houseMonk: number;
    comment: string;
    startDate: any;
    endDate: any;
    orderNo: any;
    orderName: any;
    orderDate: any;
    createDate: string | null;
    createBy: number | null;
    updateDate: string | null;
    updateBy: number | null;
    deleteDate: string | null;
    deleteBy: number | null;
    status: number | null;
    guid: string;
}